# Generated by Django 5.2.7 on 2025-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
