# Generated by Django 5.2.7 on 2025-10-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitation', '0007_alter_invitation_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gallery_event_featured', models.BooleanField(default=False)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='invitation.invitation')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-id'],
            },
        ),
    ]
