# Generated by Django 5.2.7 on 2025-10-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_invitation'),
        ('invitation', '0007_alter_invitation_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='invitation.invitation'),
        ),
    ]
