# Generated by Django 5.2.7 on 2025-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
