# Generated by Django 5.2.7 on 2025-10-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='event_audios/'),
        ),
        migrations.AddField(
            model_name='event',
            name='beginningStory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='journeyStory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='proposalStory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
