# Generated by Django 5.2.7 on 2025-11-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_audio_file_event_beginningstory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beginningStory',
            field=models.TextField(blank=True, help_text='Story displayed at the beginning of the gallery.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='journeyStory',
            field=models.TextField(blank=True, help_text='Story displayed during the journey through the gallery.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_embed',
            field=models.TextField(blank=True, help_text='Embed code for the event location map.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='proposalStory',
            field=models.TextField(blank=True, help_text='Story displayed at the proposal section of the gallery.', null=True),
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='event.event')),
            ],
        ),
    ]
