# Generated by Django 5.2.7 on 2025-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_beginningstory_alter_event_journeystory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_main_images/'),
        ),
    ]
