# Generated by Django 5.2.7 on 2026-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_event_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_guest_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of guests allowed for the event.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_main_image',
            field=models.ImageField(blank=True, help_text='Main image for the event gallery.', null=True, upload_to='event_main_images/'),
        ),
    ]
