# Generated by Django 5.2.7 on 2025-10-19 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_for', models.CharField(help_text='Name of the person the event is for', max_length=255)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('invitation_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invitation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitationtype')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
