# Generated by Django 5.2.7 on 2025-10-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='event_date',
            field=models.DateTimeField(help_text='Date and time of the event'),
        ),
        migrations.CreateModel(
            name='invitedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the invited person', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email of the invited person', max_length=254, null=True)),
                ('rsvp', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
