# Generated by Django 5.2.7 on 2025-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_invitation_event_date_invitedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedperson',
            name='full_family',
            field=models.BooleanField(default=False, help_text='Does this invitation cover the full family?'),
        ),
        migrations.AddField(
            model_name='invitedperson',
            name='person_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of people this invitation covers', null=True),
        ),
    ]
