# Generated by Django 5.2.7 on 2025-10-19 13:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_invitedperson_full_family_invitedperson_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedperson',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of the invited person', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='invitedperson',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the invited person', null=True),
        ),
        migrations.AlterField(
            model_name='invitedperson',
            name='rsvp',
            field=models.BooleanField(default=False, help_text="Has the invited person RSVP'd?"),
        ),
    ]
