# Generated by Django 5.2.7 on 2025-10-19 13:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_invitedperson_phone_number_alter_invitedperson_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedperson',
            name='family_name',
            field=models.CharField(blank=True, help_text='Family name if applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitedperson',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number of the invited person add the country code for example +1 for USA', max_length=128, null=True, region=None),
        ),
    ]
