# Generated by Django 5.2.7 on 2025-10-19 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_invitedperson_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='music_file',
            field=models.FileField(blank=True, help_text='Optional music file for the invitation', null=True, upload_to='invitations/music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac'])]),
        ),
    ]
