# Generated by Django 5.2.7 on 2025-10-19 21:11

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_invitation_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event_for',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='invitations/music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac'])]),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('person_count', models.PositiveIntegerField(default=1)),
                ('full_family', models.BooleanField(default=False)),
                ('rsvp', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitation.invitation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='invitedPerson',
        ),
    ]
