# Generated by Django 5.2.7 on 2025-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_invitation_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='has_music_file',
            field=models.BooleanField(default=False),
        ),
    ]
