# Generated by Django 5.2.7 on 2025-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_invitation_has_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
