# Generated by Django 5.2.7 on 2025-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_guest_guest_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invitation_type_image/'),
        ),
    ]
