# Generated by Django 5.2.7 on 2025-10-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_invitationtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtype',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
