# Generated by Django 5.2.7 on 2025-10-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0011_invitationtype_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='invitation_theme_image/')),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('template_path', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitationtype')),
            ],
        ),
    ]
