# Generated by Django 5.2.7 on 2025-10-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0012_invitation_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_theme',
            name='gendare',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
