# Generated by Django 5.2.7 on 2025-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_invitation_theme_gendare'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_theme',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
