# Generated by Django 5.2.7 on 2025-10-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0014_invitation_theme_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.invitation_theme'),
        ),
    ]
