# Generated by Django 5.2.7 on 2025-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0015_invitation_invitation_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
    ]
