# Generated by Django 5.2.7 on 2025-11-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0016_remove_invitation_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='music_file',
        ),
    ]
