# Generated by Django 5.2.7 on 2025-11-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0018_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='Invitation',
            new_name='invitation',
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
